#!/bin/bash

# Get SERVER IP
SERVERIP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
DOMAIN="dupper.co"

# Get opened port
PORT=$(sudo lsof -i -P -n  -p $PPID | grep $PPID | egrep .*IPv4.*LISTEN | sed -E 's/.*IPv4.*:([0-9]+) \(LISTEN\)/\1/g')

# Inform user
echo "Your port is shared at http://$(curl -s http://169.254.169.254/latest/meta-data/public-hostname):${PORT}"
echo "Press Ctrl + D to stop sharing."

if [[ ${SSH_ORIGINAL_COMMAND} == "detach" ]]; then
    tail -F /tmp/nonexistent 2>/dev/null >/dev/null
else
    cat
fi
